(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

Parameter a: Z.

Parameter b: Z.

Axiom H : (0%Z <= a)%Z.

Axiom H1 : (0%Z < b)%Z.

Parameter r: Z.

Parameter q: Z.

Axiom H2 : (((q * b)%Z + r)%Z = a).

Axiom H3 : (q <= 0%Z)%Z.

Axiom H4 : (0%Z < b)%Z.

Axiom H5 : (0%Z <= r)%Z.

Axiom H6 : (b <= r)%Z.

Parameter q1: Z.

Axiom H7 : (q1 = (q + 1%Z)%Z).

Parameter r1: Z.

Axiom H8 : (r1 = (r - b)%Z).

(* Why3 goal *)
Theorem VC_division :
  (((q1 * b)%Z + r1)%Z = a) /\
  ((q1 <= 0%Z)%Z /\ ((0%Z < b)%Z /\ (0%Z <= r1)%Z)).
Proof.


Qed.

